# Site settings
title: Windows Developer Program for IoT
email: WodContrib@microsoft.com
description: ""
baseurl: ""
url: "http://windowsondevices.com"

# Build settings
markdown: kramdown
permalink: pretty
